// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/fairusatoir/golang-gin-rest/cmd/api/config"
	"github.com/fairusatoir/golang-gin-rest/internal/clients"
	"github.com/fairusatoir/golang-gin-rest/internal/controllers/handlers"
	"github.com/fairusatoir/golang-gin-rest/internal/repositories"
	"github.com/fairusatoir/golang-gin-rest/internal/services"
)

// Injectors from wire.go:

func NewServerAPI() (*Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	productRepo := repositories.NewProductRepo(configConfig)
	datamaster, err := clients.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	productService := services.NewProductService(productRepo, datamaster)
	productHandler := handlers.NewProductHandler(productService)
	server := NewServer(configConfig, productHandler)
	return server, nil
}
